### ISSUE TITLE
How to compile in Debian stretch

### ISSUE THREAD

**Issue by ea4gmz** [martinber/noaa-apt#1]
Hello
Thanks for sharing your work. I have tried to compile your program in Debian stretch. However, rustc version in stretch is 1.24.1. I can not run "cargo" because it is not included. How could I compile it? I ran
"git clone https://github.com/martinber/noaa-apt" but I can not find very precise instructions in any case.
regards

**Comment by martinber** [comment]
Here I wrote the steps: https://github.com/martinber/noaa-apt#compiling

You should install rustup, which includes rustc, cargo and more. Anyways, have you tried the binary from https://github.com/martinber/noaa-apt/releases?

**Comment by ea4gmz** [comment]
Estimado Martín

En el repositorio de Debian stretch encuentro rustc v1.24 lo cual no incluye el programa "cargo". No hay ningún paquete con el nombre "rustup". Así que no lo puedo compilar. Me he descargado el binario y funciona correctamente con un fichero wav que bajé de la red. De modo que puedo decir que el programa me funciona. Espero poder utilizarlo a partir de grabaciones que haya con gqrx y un receptor sdr.

Gracias

   En viernes, 31 de agosto de 2018 1:13:09 CEST, martinber <notifications@github.com> escribió:  
 
 
Here I wrote the steps: https://github.com/martinber/noaa-apt#compiling

You should install rustup, which includes rustc, cargo and more. Anyways, have you tried the binary from https://github.com/martinber/noaa-apt/releases?

**Comment by martinber** [comment]
Me cambiaste de idioma jaja. Rustup se puede instalar desde https://rustup.rs/

En realidad, si conseguís cargo y rustc mayor a 1.27.0 ya está bien, no es necesario rustup. Pero parece que ahora la forma recomendada de [instalar el "lenguaje rust"](https://www.rust-lang.org/en-US/install.html) es usando rustup así que recomiendo usar eso.

Los repositorios de Debian no se pueden usar porque como decís están desactualizados.
