### ISSUE TITLE
ogg to wav

### ISSUE THREAD

**Issue by michaelachrisco** [martinber/noaa-apt#17]
At the moment, I currently use sox to convert oggs from satNOGS via:

```
$ sox satnogs_1848305_2020-03-11T17-16-41.ogg -r 11025 goodreading.wav
$ noaa-apt
```

It would be nice if the software can support ogg as a format and auto-convert if possible, just to save a step.

**Comment by michaelachrisco** [comment]
Ive never done rust but it appears that this library/crate does what I am suggesting: https://github.com/RustAudio/audrey

Might take a stab at it at some point...

**Comment by martinber** [comment]
Hi,

How does satNOGS work? By visiting the website I can't understand its purpose.

Does satNOGS somehow do recordings in OGG? I'm wondering how useful this feature would be, and which audio codecs are commonly used.

**Comment by michaelachrisco** [comment]
So im basically running the same setup as this project: 
https://www.raspberrypi.org/blog/build-a-satnogs-ground-station-raspberry-pi-3b-hackspace-magazine-18/

It allows you to run your own satellite observation/tracker. It does everything from getting noaa sat images, getting instrument readings, and helping out the creators of the satellites via an open source project. The way you get the readings is to set up a raspberry pi (or any computer really), run the software, and the software will get everything in ogg format. Here are some good examples:

Example above: https://network.satnogs.org/observations/1848305/ 
Audio file link is at the bottom: 
![image](https://user-images.githubusercontent.com/398491/76653370-c7e39e80-6525-11ea-925f-2a3b10ed5a5f.png)

Im not sure what they use ATM (probably wxtoimg) but it outputs the image in the "data" tab of the website: 
![image](https://user-images.githubusercontent.com/398491/76653669-5e17c480-6526-11ea-97cb-5b0c8592ed2c.png)


It would be cool if I could hook up the tool to satNOGS and at least verify their findings in an open source way (such as your tool) or even have it completely replace wxtoimg overtime. Maybe. I'm kinda new to this whole "taking weather satellite" thing :)

**Comment by martinber** [comment]
I will keep your suggestion in mind. Some notes:

- Looks like [satNOGS has its own APT decoder](https://gitlab.com/librespacefoundation/satnogs/gr-satnogs/-/blob/master/lib/noaa_apt_sink_impl.cc). It's not using WXtoIMG

- The recording you linked is encoded with Vorbis (I think that OGG files sometimes have a different codec inside. e.g. Opus)

**Comment by michaelachrisco** [comment]
Oh wow TIL. Well then, it would seem that this request would not make sense given the context. Ill go ahead and close it out. Thanks for building the tool!
