### ISSUE TITLE
Consider formatting code using rustfmt

### ISSUE THREAD

**Issue by Arcadie** [martinber/noaa-apt#22]
What are your thoughts on using [rustfmt](https://github.com/rust-lang/rustfmt) to format code automatically? [(motivation)](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md#motivation---why-use-a-formatting-tool)
Most editors support this (format on save), and paired with [rust-analyzer](https://rust-analyzer.github.io/), it improves the experience a lot.

Example diff, code formatted with rustfmt and type hints by rust analyzer on the right:

<img width="1007" alt="rustfmt_and_analyzer" src="https://user-images.githubusercontent.com/1472875/89303195-88545500-d674-11ea-8c7e-47c7b3a9afdb.png">

It's as simple as running `cargo fmt` on the current codebase.
Also, I highly recommend [rust-analyzer](https://rust-analyzer.github.io/) instead of the [Rust Language Server (RLS)](https://github.com/rust-lang/rls) for a nicer experience.

**Comment by martinber** [comment]
Yes, you are right. I regret using 80 chars instead of 100, and not using rustfmt before. I thought about a few months ago and I'm afraid that it will leave a mess, because sometimes we know better than rustfmt. I will spend an hour or two fixing things, but it's not that bad.

The biggest problem is that what happens when I fix the problems? rustfmt will revert my changes again? Should we use `#[rustfmt::skip]` a few times? I should look at what are most projects doing.

Few examples where it makes things worse:

![Screenshot at 2020-08-04 19-47-14](https://user-images.githubusercontent.com/6921727/89353528-f3118a80-d68c-11ea-921d-9d7b04feae46.png)
![Screenshot at 2020-08-04 19-47-14](https://user-images.githubusercontent.com/6921727/89353535-f6a51180-d68c-11ea-8ad2-f0aeadf84fa5.png)
![Screenshot at 2020-08-04 19-42-49](https://user-images.githubusercontent.com/6921727/89353581-0ae90e80-d68d-11ea-8c77-a225f2b311cc.png)

**Comment by Arcadie** [comment]
> The biggest problem is that what happens when I fix the problems? rustfmt will revert my changes again? 

Well, `cargo fmt` formats all the code (and I use `"editor.formatOnSave": true` in VSCode), so there isn't really a way to "fix" problems. **It will revert the changes** to a default and consistent code style every time.

You can make [small tweaks](https://rust-lang.github.io/rustfmt/?version=master&search=) by adding a `.rustfmt.toml` file:

```toml
max_width = 100
```

Other examples on github: https://github.com/search?q=filename:rustfmt.toml

The advantage is that there is one less thing to worry about: code formatting.
It takes care of trailing commas on last matching arm or array item, where the closing parentheses go, etc...

Some things "feel wrong", when some lines are wrapped, some are not:

```rust
    assert_abs_diff_eq!(
        distance((0., PI / 6.), (0., 0.)),
        PI / 6.,
        epsilon = tolerance
    );
    assert_abs_diff_eq!(distance((0., 0.), (PI, 0.)), PI, epsilon = tolerance);
```

And sometimes it's nice to have lines "align" just the right way, but once you let it do it's thing, you get used to it.

To address the issues you pointed out (and I agree, there are more cases like this), you could write the first part (`state.rs`) like this:

```rust
use glib::object::{IsA, Object};
fn get_object<T: IsA<Object>>(builder: &gtk::Builder, name: &str) -> T {
    builder
        .get_object(name)
        .expect(&*format!("Couldn't get {}", name))
}

/// ...

    main_paned: get_object(&builder, "main_paned"),
    main_progress_bar: get_object(&builder, "main_progress_bar"),
    main_stack: get_object(&builder, "main_stack"),
    dec_stack_child: get_object(&builder, "dec_stack_child"),
    res_stack_child: get_object(&builder, "res_stack_child"),
    ts_stack_child: get_object(&builder, "ts_stack_child"),

/// ...
```

For the second one, as a workaround, `//` can be used at the end of the line to prevent wrapping. It's not perfect, but it's something:

```rust
fn test_sample_sync_frame() {
    assert_eq!(
        vec![
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, //
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, //
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, //
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, //
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, //
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, //
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, //
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, //
        ],
        generate_sync_frame(Rate::hz(FINAL_RATE * 5)).unwrap()
    );
}
```

I don't have very strong feelings about this, it's just a quality of life improvement, one less thing to keep in mind when changing something without having to worry about matching the coding style. I didn't even notice this section on the [website](https://noaa-apt.mbernardi.com.ar/development.html#code-style) until now. I usually looked at the surrounding code and tried to match it.

So it's really your call and how comfortable you feel with it.

**Comment by martinber** [comment]
Thanks, I will keep in mind to start using it. But first I will mark some tests and sections with `#[rustfmt::skip]`. For example the first image (`/src/gui/state.rs`)

**Comment by martinber** [comment]
Done
