### ISSUE TITLE
arm64 release binaries needed

### ISSUE THREAD

**Issue by mgrouch** [martinber/noaa-apt#33]
arm64 release binaries needed.

Might be set it up on launchpad.net?

Thanks

**Comment by martinber** [comment]
Hello. I never thought of using launchpad, it might be a good idea. I guess I can use https://build.opensuse.org/ or play a bit more with the cross compiling docker.

What devices are using arm64? Raspberry Pi 4?

**Comment by mgrouch** [comment]
I’ve managed to build it on CircleCi and deployed it on cloudsmith. 
You can look at changes in my fork. 
Launchpad didn’t work cause it doesn’t let download external cargo 
packages.

**Comment by mgrouch** [comment]
﻿I’ve created a pull request

**Comment by mgrouch** [comment]
https://github.com/martinber/noaa-apt/pull/35

**Comment by martinber** [comment]
Thanks! I have to think if I prefer to do it via my Docker or via an external service like CircleCI. But this is going to be very useful anyways

**Comment by martinber** [comment]
Hello, I started to build for Raspberry Pi 4 (also named aarch64 or arm64). Can you try it? It should be a matter of [downloading the zip](https://github.com/martinber/noaa-apt/releases/download/v1.4.0/noaa-apt-1.4.0-aarch64-linux-gnu.zip), extracting and running.

**Comment by mgrouch** [comment]
I’m including a build of noaa-apt arm64
into my BBN Marine OS. 
You can see the scripts how it’s done here

https://github.com/bareboat-necessities/lysmarine_gen#what-is-lysmarine-bbn-edition
