### ISSUE TITLE
Some output images are rotated 180 degrees

### ISSUE THREAD

**Issue by itsmaxymoo** [martinber/noaa-apt#5]
This is the only good pass I was able to record, which is why I said "some output images". In this pass, the weather satellite went from **south to north**, which may have something to do with it (?).

[Here is a link to the WAV file](https://drive.google.com/open?id=10XAEadQMWywNYtFgW_LrcWJomiYOE-c8).

![gqrx_20190824_220748_137100000](https://user-images.githubusercontent.com/40216804/63649733-5ff77300-c70f-11e9-932b-8cc5f98cf852.png)

As you can see, the Great Lakes are rotated 180 degrees.

**Comment by Imperator26** [comment]
'In this pass, the weather satellite went from south to north'

It is definitely because of this

**Comment by martinber** [comment]
Yes, the program has no way to know if the satellite went from south to north and rotate the image accordingly. The only way to determine the direction of the pass is to get the time and calculate the orbit of the satellite (WXtoIMG does this) but is quite a lot of work.

Thank you to both of you.

**Comment by itsmaxymoo** [comment]
I see... If that is the case, would a simple drop-down specifying "North-South" or "South-North" do the trick? Of course the user would have to know for themselves, but it's better than nothing!

**Comment by martinber** [comment]
I think that would be useful, I'm going to do it when I have time

**Comment by Arcadie** [comment]
I poked a this issue today: (link to pull request) -> https://github.com/martinber/noaa-apt/pull/9

Added a command line option `--rotate-image` and a checkbox to `Advanced settings`:

<img width="449" alt="updated-gui" src="https://user-images.githubusercontent.com/1472875/72998155-0d2cff00-3e06-11ea-850a-021eb08df97f.png">

The result:

![noaa-apt-great-lakes](https://user-images.githubusercontent.com/1472875/72998175-18802a80-3e06-11ea-93da-128366d5202b.png)

**Comment by martinber** [comment]
Solved by @Arcadie on #9. Thank you to everyone!
