### ISSUE TITLE
noaa-apt running on aarch64 22.04 (pi4)

### ISSUE THREAD

**Issue by alphafox02** [martinber/noaa-apt#52]
After pulling down the latest noaa-apt zip file, noaa-apt-1.4.0-armv7-linux-gnueabihf, and performing the following on DragonOS Pi64

sudo dpkg --add-architecture armhf
sudo apt-get update
sudo apt-get install libc6:armhf libisl23:armhf libmpfr6:armhf libmpc3:armhf libstdc++6:armhf libgtk-3-0:armhf

I was able to launch and use the noaa-apt gui. It would be nice if in the future it could run without the armhf packages (takes up 100+ MB of storage). 

Confirmed working with the included wav files in the test folder.

**Comment by alphafox02** [comment]
Not all of those packages may be needed, it’s just what I happened to have installed. If I get a chance I’ll remove unnecessary ones from the list.

**Comment by martinber** [comment]
Thanks for this post! I should provide downloads for raspberry pi 4 in the future

**Comment by alphafox02** [comment]
That’ll be great! I did however end up needing some of the packages I installed for NexMon so it ended up working out fine, just needed the libgtk additionally.

**Comment by martinber** [comment]
Hello, I started to build for Raspberry Pi 4 (also named aarch64 or arm64). Can you try it? It should be a matter of [downloading the zip](https://github.com/martinber/noaa-apt/releases/download/v1.4.0/noaa-apt-1.4.0-aarch64-linux-gnu.zip), extracting and running.

**Comment by alphafox02** [comment]
Sorry I didn’t see this till now! I’ll give it a try this weekend.

**Comment by alphafox02** [comment]
Slight problem with the zip,

```
Error loading settings file "/home/ubuntu/.config/noaa-apt/settings.toml": No such file or directory (os error 2)
Saving default settings to "/home/ubuntu/.config/noaa-apt/settings.toml"
thread 'main' panicked at 'Couldn't load resource icon.png: Error { domain: g-file-error-quark, code: 4, message: "Failed to open file “/usr/share/noaa-apt/icon.png”: No such file or directory" }', src/gui/state.rs:252:92
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After making the /usr/share/noaa-apt directory and then copying the icon.png i found in the res folder it ran on the Pi4 w/ aarch64 22.04.

**Comment by martinber** [comment]
Oh thanks for letting me know, it was a stupid mistake

I've fixed it now. So I guess that I'm finished with aarch64
